// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PedidosVendas.Infrastructure.Persistence;

#nullable disable

namespace PedidosVendas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PedidosVendasDbContext))]
    partial class PedidosVendasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Cupom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IdCategoria")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCupomProduto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PercDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMinimoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DataValidade");

                    b.ToTable("Cupom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_DescontoExclusivo", "(\"ValorDesconto\" > 0 AND \"PercDesconto\" = 0) OR (\"PercDesconto\" > 0 AND \"ValorDesconto\" = 0)");

                            t.HasCheckConstraint("CK_Cupom_QuantidadeNaoNegativa", "\"Quantidade\" >= 0");
                        });
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.CupomProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCupom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdCupom", "IdProduto")
                        .IsUnique();

                    b.ToTable("CupomProduto", (string)null);
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.FormaPagto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("QtdMaximaParcelas")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Descricao")
                        .IsUnique();

                    b.ToTable("FormaPagto", null, t =>
                        {
                            t.HasCheckConstraint("CK_FormaPagto_QtdMinima", "\"QtdMaximaParcelas\" >= 1");
                        });
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("IdCliente")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdCupom")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUnidade")
                        .HasColumnType("uuid");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "IdCliente", "Status");

                    b.ToTable("Pedido", (string)null);
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.ProdutosPedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<decimal>("ValorUnitario")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdPedido", "IdProduto")
                        .IsUnique();

                    b.ToTable("ProdutosPedido", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProdutosPedido_QuantidadePositiva", "\"Quantidade\" > 0");
                        });
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.TenantFormaPagtoConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdFormaPagto")
                        .HasColumnType("uuid");

                    b.Property<int>("QtdMaximaParcelasOverride")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdFormaPagto");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IdFormaPagto")
                        .IsUnique();

                    b.ToTable("TenantFormaPagtoConfig", null, t =>
                        {
                            t.HasCheckConstraint("CK_TenantFormaPagtoConfig_QtdMinima", "\"QtdMaximaParcelasOverride\" >= 1");
                        });
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.CupomProduto", b =>
                {
                    b.HasOne("PedidosVendas.Domain.Entities.Cupom", "Cupom")
                        .WithMany("CupomProdutos")
                        .HasForeignKey("IdCupom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.ProdutosPedido", b =>
                {
                    b.HasOne("PedidosVendas.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Itens")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.TenantFormaPagtoConfig", b =>
                {
                    b.HasOne("PedidosVendas.Domain.Entities.FormaPagto", "FormaPagto")
                        .WithMany()
                        .HasForeignKey("IdFormaPagto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormaPagto");
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Cupom", b =>
                {
                    b.Navigation("CupomProdutos");
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
