// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PedidosVendas.Infrastructure.Persistence;

#nullable disable

namespace PedidosVendas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PedidosVendasDbContext))]
    partial class PedidosVendasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Cupom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("IdCategoria")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCupomProduto")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PercDesconto")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("integer");

                    b.Property<uint>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorDesconto")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ValorMinimoCompra")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "DataValidade");

                    b.ToTable("Cupom", null, t =>
                        {
                            t.HasCheckConstraint("CK_Cupom_DescontoExclusivo", "(\"ValorDesconto\" > 0 AND \"PercDesconto\" = 0) OR (\"PercDesconto\" > 0 AND \"ValorDesconto\" = 0)");

                            t.HasCheckConstraint("CK_Cupom_QuantidadeNaoNegativa", "\"Quantidade\" >= 0");
                        });
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.CupomProduto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdCupom")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdProduto")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdProduto");

                    b.HasIndex("IdCupom", "IdProduto")
                        .IsUnique();

                    b.ToTable("CupomProduto", (string)null);
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.CupomProduto", b =>
                {
                    b.HasOne("PedidosVendas.Domain.Entities.Cupom", "Cupom")
                        .WithMany("CupomProdutos")
                        .HasForeignKey("IdCupom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cupom");
                });

            modelBuilder.Entity("PedidosVendas.Domain.Entities.Cupom", b =>
                {
                    b.Navigation("CupomProdutos");
                });
#pragma warning restore 612, 618
        }
    }
}
